### PR TITLE
Bugfix/upco 167

### PR DESCRIPTION
**Pull request by NicolasYapla**
## PR Checklist

This PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/antwerp-ui_angular/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A [changelog entry](https://github.com/digipolisantwerp/antwerp-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by PieterVanderhaegen — APPROVED** [review]

**Review by TriangleJuice — COMMENTED** [review]
@NicolasYapla Waarom de lege tsconfig.json files? Verder lijkt deze PR in orde.

**Comment by NicolasYapla** [comment]
Volgens de commit voor Linter warnings, ik check even met Arthur.

**Review by TriangleJuice — CHANGES_REQUESTED** [review]
Linter warings graag anders oplossen.

**Comment by NicolasYapla** [comment]
@TriangleJuice Heb de lege tsconfig files verwijdert en heb geen Linter errors, dus ik denk dat het opgelost is.

**Review by TriangleJuice — APPROVED** [review]

**Comment by TriangleJuice** [comment]
@NicolasYapla top! Enkel nog de merge conflicts oplossen en we zijn idd klaar voor een release.

**Pull request merged**
