### PR TITLE
fix: Added detectChanges on the flyout open method & possibility to o…

### PR DESCRIPTION
**Pull request by FiestaRuless**
## PR Checklist

This PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Contributing guidelines](https://github.com/digipolisantwerp/antwerp-ui_angular/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] A [changelog entry](https://github.com/digipolisantwerp/antwerp-ui_angular/blob/master/guidelines/CHANGELOG.md) was added

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When using ngx-forms it's datepicker, a flyout is used to open the calendar. This can be done by clicking on the icon but the method open() also exists so you can open using code. When this method is called, the state gets changed and the value 'this.isOpened' is changed to true. But the HostBinding does not update and set the class 'is-open'. The updated value didn't persist to the view. DetectChanges was added to update the view.

Issue Number: N/A

## What is the new behavior?
When directly calling the open() method, the class 'is-open' is added.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by TriangleJuice — CHANGES_REQUESTED** [review]
Tests aren't working atm. Thanks for fixing that!

**Comment by FiestaRuless** [comment]
Yea I noticed that when running it locally.
But the error is of something withing node_modules/@types/node.
Doesn't really have something to do with my changes so I'm not really sure how to solve this?
Should I update that specific package?

**Comment by TriangleJuice** [comment]
Hey @FiestaRuless ik heb het probleem opgelost op de master branch. Je kan deze gewoon binnentrekken en pushen en de CI zou terug moeten werken.

**Comment by FiestaRuless** [comment]
@TriangleJuice 
Normaal zou hem gemerged moeten zijn

**Review by NicolasYapla — APPROVED** [review]

**Comment by NicolasYapla** [comment]
Merged in and published under version 6.0.5.

**Comment by FiestaRuless** [comment]
Moet deze ook gepulished worden op https://nexusrepo.antwerpen.be/service/rest/repository/browse/npm-all/%40acpaas-ui/ngx-flyout/ bijvoorbeeld?

**Comment by TriangleJuice** [comment]
Nee, de nexusrepo zou deze relatief onmiddellijk moeten oppikken van npmjs.

**Pull request merged**
